-- blue -16776961
-- yellow -256
-- red -65536
-- black -16777216
-- green -16711936


insert into trails (id, colour, first_point, last_point, first_to_last_time, last_to_first_time) values 
	(1, -65536, (select id from places where name = 'Małołączniak'), (select id from places where name = 'Kopa Kondracka'), 35, 45),
	(2, -65536, (select id from places where name = 'Kopa Kondracka'), (select id from places where name = 'Przełęcz pod Kopą Kondracką'), 20, 30),
	(3, -65536, (select id from places where name = 'Przełęcz pod Kopą Kondracką'), (select id from places where name = 'Kasprowy Wierch'), 95, 100),
	(4, -65536, (select id from places where name = 'Kasprowy Wierch'), (select id from places where name = 'Przełęcz Liliowe'), 25, 25),
	(5, -65536, (select id from places where name = 'Przełęcz Liliowe'), (select id from places where name = 'Przełęcz Świnicka'), 30, 25),
	(6, -65536, (select id from places where name = 'Przełęcz Świnicka'), (select id from places where name = 'Świnica'), 60,45),
	(7, -65536, (select id from places where name = 'Świnica'), (select id from places where name = 'Zawrat'),  45, 60),
	(8, -65536, (select id from places where name = 'Zawrat'), (select id from places where name = 'Kozia Przełęcz'), 110, null), 
	(9, -65536, (select id from places where name = 'Kozia Przełęcz'), (select id from places where name = 'Kozi Wierch'), 90, null),
	(10, -65536, (select id from places where name = 'Kozi Wierch'), (select id from places where name = 'Żleb Kulczyńskiego'), 60, 45),
	(11, -65536, (select id from places where name = 'Żleb Kulczyńskiego'),(select id from places where name = 'Zadni Granat'), 25, 25),
	(12, -65536, (select id from places where name = 'Zadni Granat'),(select id from places where name = 'Skrajny Granat'), 25, 25),
	(13, -65536, (select id from places where name = 'Skrajny Granat'),(select id from places where name = 'Krzyżne'), 25, 25),
	(30, -65536, (select id from places where name = 'Parking Dolina Strążyska'), (select id from places where name = 'Polana Strążyska'), 40, 35),
	(31, -65536, (select id from places where name = 'Polana Strążyska'), (select id from places where name = 'Przełęcz w Grzybowcu'), 40, 35),
	(32, -65536, (select id from places where name = 'Przełęcz w Grzybowcu'), (select id from places where name = 'Wyżnia Przełęcz Kondracka'), 105, 80),
	(14, -16777216, (select id from places where name = 'Żleb Kulczyńskiego'), (select id from places where name = 'Kozia Dolinka'), 30, 45),
	(21, -16777216, (select id from places where name = 'Odejście na Kozi Wierch'), (select id from places where name = 'Kozi Wierch'), 95, 60),
	(22, -16777216, (select id from places where name = 'Rzeżuchy'), (select id from places where name = 'Dolina Pięciu Stawów'), 40, 25),
	(23, -16777216, (select id from places where name = 'Czarny Staw Gąsienicowy'), (select id from places where name = 'Karb'), 40, 30),
	(24, -16777216, (select id from places where name = 'Karb'), (select id from places where name = 'Kościelec'), 50, 50),
	(47, -16777216, (select id from places where name = 'Parking Brzeziny'), (select id from places where name = 'Psia Trawka'), 50, 40),
	(15, -16711936,(select id from places where name = 'Nad Zmarzłym Stawem'), (select id from places where name = 'Kozia Dolinka'), 10, 10),
	(16, -16711936,(select id from places where name = 'Kozia Dolinka'), (select id from places where name = 'Zadni Granat'), 50, 35),
	(26, -16711936,(select id from places where name = 'Dwoiśniak'), (select id from places where name = 'Przełęcz Liliowe'), 50, 35),
	(33, -16711936, (select id from places where name = 'Wylot za Bramką'), (select id from places where name = 'Dolina za Bramką'), 20, 20),
	(34, -16711936, (select id from places where name = 'Polana Strążyska'), (select id from places where name = 'Siklawica'), 10, 10),
	(38, -16711936, (select id from places where name = 'Schronisko na Hali Kondratowej'), (select id from places where name = 'Przełęcz pod Kopą Kondracką'), 105, 70),
	(17, -256, (select id from places where name = 'Odejście na Kozią Przełęcz'), (select id from places where name = 'Kozia Przełęcz'), 90, 60),
	(18, -256, (select id from places where name = 'Zmarzły Staw'), (select id from places where name = 'Nad Zmarzłym Stawem'), 10, 10),
	(19, -256, (select id from places where name = 'Nad Zmarzłym Stawem'), (select id from places where name = 'Kozia Przełęcz'), 50, 40),
	(20, -256, (select id from places where name = 'Odejście na Skrajny Granat'), (select id from places where name = 'Skrajny Granat'), 100, 75),
	(27, -256, (select id from places where name = 'Pustelnia św. Brata Alberta'), (select id from places where name = 'Klasztor Albertynów'), 10, 10),
	(28, -256, (select id from places where name = 'Dolina Białego'), (select id from places where name = 'Polana Białego'), 70, 55),
	(35, -256, (select id from places where name = 'Dolina Małej Łąki'), (select id from places where name = 'Rówienki'), 20, 15),
	(36, -256, (select id from places where name = 'Rówienki'), (select id from places where name = 'Przełęcz Kondracka'), 20, 15),
	(37, -256, (select id from places where name = 'Przełęcz Kondracka'), (select id from places where name = 'Kopa Kondracka'), 45, 30),
	(25, -16776961, (select id from places where name = 'Zielony Staw Gąsienicowy'), (select id from places where name = 'Karb'), 30, 20),
	(29, -16776961, (select id from places where name = 'Dolina ku Dziurze'), (select id from places where name = 'Jaskinia Dziura'), 20, 15),
	(39, -16776961, (select id from places where name = 'Kuźnice'), (select id from places where name = 'Pustelnia św. Brata Alberta'), 15, 10),
	(40, -16776961, (select id from places where name = 'Pustelnia św. Brata Alberta'), (select id from places where name = 'Polana Kalatówki'), 25, 20),
	(41, -16776961, (select id from places where name = 'Pustelnia św. Brata Alberta'), (select id from places where name = 'Polana Kalatówki'), 10, 10),
	(42, -16776961, (select id from places where name = 'Polana Kalatówki'), (select id from places where name = 'Schronisko na Hali Kondratowej'), 45, 35),
	(43, -16776961, (select id from places where name = 'Schronisko na Hali Kondratowej'), (select id from places where name = 'Przełęcz Kondracka'), 80, 60),
	(44, -16776961, (select id from places where name = 'Przełęcz Kondracka'), (select id from places where name = 'Wyżnia Przełęcz Kondracka'), 10, 10),
	(45, -16776961, (select id from places where name = 'Wyżnia Przełęcz Kondracka'), (select id from places where name = 'Giewont'), 15, null),
	(46, -16776961, (select id from places where name = 'Giewont'), (select id from places where name = 'Wyżnia Przełęcz Kondracka'), 10, null),
	(48, -16777216, (select id from places where name = 'Psia Trawka'), (select id from places where name = 'Schronisko Murowaniec, Hala Gąsienicowa'), 105, 80),
(49, -16777216, (select id from places where name = 'Nad Murowańcem'), (select id from places where name = 'Gąsienicowa kolejka krzesełkowa'), 35, 25),
(50, -16777216, (select id from places where name = 'Gąsienicowa kolejka krzesełkowa'), (select id from places where name = 'Zielony Staw Gąsienicowy'), 45, 30),
(51, -16777216, (select id from places where name = 'Zielony Staw Gąsienicowy'), (select id from places where name = 'Przełęcz Świnicka'), 50, 35),
(52, -65536, (select id from places where name = 'Parking Palenica Białczańska'), (select id from places where name = 'Las pod Wołoszynem'), 45, 35),
(53, -65536, (select id from places where name = 'Las pod Wołoszynem'), (select id from places where name = 'Wodogrzmoty Mickiewicza'), 5, 5),
(54, -65536, (select id from places where name = 'Wodogrzmoty Mickiewicza'), (select id from places where name = 'Żabie Oko'), 90, 70),
(55, -16776961, (select id from places where name = 'Żabie Oko'), (select id from places where name = 'Schronisko Morskie Oko'), 5, 5),
(56, -65536, (select id from places where name = 'Schronisko Morskie Oko'), (select id from places where name = 'Szeroki Piarg'), 20, 20),
(57, -65536, (select id from places where name = 'Schronisko Morskie Oko'), (select id from places where name = 'Szeroki Piarg'), 30, 30),
(58, -65536, (select id from places where name = 'Szeroki Piarg'), (select id from places where name = 'Czarny Staw pod Rysami'), 30, 20),
(59, -65536, (select id from places where name = 'Czarny Staw pod Rysami'), (select id from places where name = 'Rysy'), 190, 155),
(60, -16711936, (select id from places where name = 'Czarny Staw pod Rysami'), (select id from places where name = 'Przełęcz pod Chłopkiem'), 165, 130),
(61, -256, (select id from places where name = 'Schronisko Morskie Oko'), (select id from places where name = 'Płaśń pod Mnichem'), 75, 60),
(62, -65536, (select id from places where name = 'Płaśń pod Mnichem'), (select id from places where name = 'Wrota Chałubińskiego'), 55, 40),
(63, -256, (select id from places where name = 'Płaśń pod Mnichem'), (select id from places where name = 'Szpiglasowa Przełęcz'), 60, 45),
(64, -256, (select id from places where name = 'Szpiglasowa Przełęcz'), (select id from places where name = 'Szpiglasowy Wierch'), 15, 10),
(65, -256, (select id from places where name = 'Odejście na Szpiglasową Przełęcz'), (select id from places where name = 'Szpiglasowa Przełęcz'), 95, 75),
(66, -16711936, (select id from places where name = 'Wodogrzmoty Mickiewicza'), (select id from places where name = 'Schronisko w Roztoce'), 10, 15),
(67, -16711936, (select id from places where name = 'Wodogrzmoty Mickiewicza'), (select id from places where name = 'Rzeżuchy'), 85, 65),
(68, -16711936, (select id from places where name = 'Rzeżuchy'), (select id from places where name = 'Wielki Staw'), 45, 30),
(69, -16776961, (select id from places where name = 'Wielki Staw'), (select id from places where name = 'Odejście na Krzyżne'), 5, 5),
(70, -16711936, (select id from places where name = 'Kuźnice'), (select id from places where name = 'Myślenickie Turnie'), 75, 55),
(71, -16711936, (select id from places where name = 'Myślenickie Turnie'), (select id from places where name = 'Kasprowy Wierch'), 120, 85),
(72, -256, (select id from places where name = 'Kuźnice'), (select id from places where name = 'Przełęcz między Kopami'), 80, 55),
(73, -16776961, (select id from places where name = 'Kuźnice'), (select id from places where name = 'Odejście na Nosalową Przełęcz'), 15, 10),
(74, -16776961, (select id from places where name = 'Odejście na Nosalową Przełęcz'), (select id from places where name = 'Przełęcz między Kopami'), 70, 45),
(75, -16711936, (select id from places where name = 'Odejście na Nosalową Przełęcz'), (select id from places where name = 'Nosalowa Przełęcz'), 20, 15),
(76, -16711936, (select id from places where name = 'Nosalowa Przełęcz'), (select id from places where name = 'Nosal'), 15, 10),
(77, -16711936, (select id from places where name = 'Murowanica'), (select id from places where name = 'Nosal'), 55, 45),
(78, -16711936, (select id from places where name = 'Parking Jaszczurówka'), (select id from places where name = 'Olczyska Polana'), 45, 30),
(79, -256, (select id from places where name = 'Olczyska Polana'), (select id from places where name = 'Nosalowa Przełęcz'), 30, 20),
(80, -16711936, (select id from places where name = 'Olczyska Polana'), (select id from places where name = 'Polana Kopieniec'), 40, 30),
(81, -16711936, (select id from places where name = 'Polana Kopieniec'), (select id from places where name = 'Wielki Kopieniec'), 15, 10),
(82, -16711936, (select id from places where name = 'Wielki Kopieniec'), (select id from places where name = 'Krzyż pod Kopieńcem'), 15, 15),
(83, -16711936, (select id from places where name = 'Polana Kopieniec'), (select id from places where name = 'Krzyż pod Kopieńcem'), 20, 20),
(85, -65536, (select id from places where name = 'Parking Toporowa Cyrhla'), (select id from places where name = 'Odejście na Psią Trawkę'), 30, 20),
(86, -16711936, (select id from places where name = 'Odejście na Psią Trawkę'), (select id from places where name = 'Krzyż pod Kopieńcem'), 15, 15),
(87, -65536, (select id from places where name = 'Odejście na Psią Trawkę'), (select id from places where name = 'Psia Trawka'), 40, 35),
(88, -65536, (select id from places where name = 'Las pod Wołoszynem'), (select id from places where name = 'Polana pod Wołoszynem'), 45, 35),
(89, -65536, (select id from places where name = 'Polana pod Wołoszynem'), (select id from places where name = 'Rowień Waksmundzka'), 55, 45),
(90, -65536, (select id from places where name = 'Rowień Waksmundzka'), (select id from places where name = 'Psia Trawka'), 45, 60),
(91, -16711936, (select id from places where name = 'Rowień Waksmundzka'), (select id from places where name = 'Gęsia Szyja'), 25, 20),
(92, -16711936, (select id from places where name = 'Rusinowa Polana'), (select id from places where name = 'Gęsia Szyja'), 35, 25),
(93, -16777216, (select id from places where name = 'Polana pod Wołoszynem'), (select id from places where name = 'Czerwone Brzeżki'), 30, 30),
(94, -16776961, (select id from places where name = 'Parking Palenica Białczańska'), (select id from places where name = 'Czerwone Brzeżki'), 45, 35),
(95, -16776961, (select id from places where name = 'Czerwone Brzeżki'), (select id from places where name = 'Rusinowa Polana'), 10, 10),
(96, -16711936, (select id from places where name = 'Parking Wierch Poroniec'), (select id from places where name = 'Rusinowa Polana'), 60, 50),
(97, -16776961, (select id from places where name = 'Parking Zazadnia'), (select id from places where name = 'Rusinowa Polana'), 80, 55),
(98, -16711936, (select id from places where name = 'Rowień Waksmundzka'), (select id from places where name = 'Wolarczyska'), 60, 50),
(99, -16711936, (select id from places where name = 'Wolarczyska'), (select id from places where name = 'Las Gąsienicowy'), 55, 65),
(100, -16777216, (select id from places where name = 'Wolarczyska'), (select id from places where name = 'Dolina Pańszczyca'), 25, 20),
(101, -16777216, (select id from places where name = 'Wolarczyska'), (select id from places where name = 'Dolina Pańszczyca'), 25, 20),
(102, -256, (select id from places where name = 'Dolina Pańszczyca'), (select id from places where name = 'Krzyżne'), 115, 85),
(103, -256, (select id from places where name = 'Dolina Pańszczyca'), (select id from places where name = 'Las Gąsienicowy'), 45, 55),
(104, -256, (select id from places where name = 'Las Gąsienicowy'), (select id from places where name = 'Schronisko Murowaniec, Hala Gąsienicowa'), 5, 5),
(105, -256, (select id from places where name = 'Odejście na Krzyżne'), (select id from places where name = 'Krzyżne'), 115, 75),
(106, -16776961, (select id from places where name = 'Żabie Oko'), (select id from places where name = 'Dolina Pięciu Stawów'), 110, 100),
(107, -16776961, (select id from places where name = 'Dolina Pięciu Stawów'), (select id from places where name = 'Wielki Staw'), 5, 5),
(108, -16776961, (select id from places where name = 'Wielki Staw'), (select id from places where name = 'Odejście na Krzyżne'), 5, 5),
(109, -16776961, (select id from places where name = 'Odejście na Krzyżne'), (select id from places where name = 'Odejście na Kozi Wierch'), 10, 10),
(110, -16776961, (select id from places where name = 'Odejście na Kozi Wierch'), (select id from places where name = 'Odejście na Szpiglasową Przełęcz'), 5, 5),
(111, -16776961, (select id from places where name = 'Odejście na Szpiglasową Przełęcz'), (select id from places where name = 'Odejście na Kozią Przełęcz'), 5, 5),
(112, -16776961, (select id from places where name = 'Odejście na Kozią Przełęcz'), (select id from places where name = 'Zawrat'), 75, 55),
(113, -16776961, (select id from places where name = 'Zmarzły Staw'), (select id from places where name = 'Zawrat'), 70, 50),
(114, -16776961, (select id from places where name = 'Odejście na Skrajny Granat'), (select id from places where name = 'Zmarzły Staw'), 20, 20),
(115, -16776961, (select id from places where name = 'Czarny Staw Gąsienicowy'), (select id from places where name = 'Odejście na Skrajny Granat'), 15, 15),
(116, -16777216, (select id from places where name = 'Parking Łysa Polana'), (select id from places where name = 'Parking Palenica Białczańska'), 20, 20),
(117, -16776961, (select id from places where name = 'Parking Łysa Polana'), (select id from places where name = 'Pod Wielickim Szczytem'), 310, 255),
(118, -16776961, (select id from places where name = 'Parking Łysa Polana'), (select id from places where name = 'Pod Wielickim Szczytem'), 310, 255),
(119, -16711936, (select id from places where name = 'Pod Wielickim Szczytem'), (select id from places where name = 'Polski Grzebień'), 20, 15),
(120, -256, (select id from places where name = 'Polski Grzebień'), (select id from places where name = 'Mała Wysoka'), 50, 35),
(121, -16711936, (select id from places where name = 'Śląski Dom'), (select id from places where name = 'Polski Grzebień'), 170, 130),
(122, -16776961, (select id from places where name = 'Pod Wielickim Szczytem'), (select id from places where name = 'Rohatka'), 60, 40),
(123, -16776961, (select id from places where name = 'Zbójnicka Chata'), (select id from places where name = 'Rohatka'), 100, 75),
(124, -16711936, (select id from places where name = 'Gąsienicowa kolejka krzesełkowa'), (select id from places where name = 'Dwoiśniak'), 10, 10),
(125, -256, (select id from places where name = 'Dwoiśniak'), (select id from places where name = 'Kasprowy Wierch'), 60, 40);
